version: '3.8'

services: 

  client:
    build: 
      context: ./Client
    ports:
      - "8080:8080"
  
  server:
    build: 
      context: ./Server
    ports:
      - "3030:3030"
    depends_on:
      - mongo
      - redis
    environment:
      SERVER_PORT: 3030
      MONGO_URI: "mongodb://mongo:27017/auth"
      secret_key: "FBQ7ujQq96eGEF1lZiOxLWAg+ue6wV0H45C0ythHpF4"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes: 
      - redis-data:/data  

volumes:
  mongo-data:
  redis-data:
